# Generated by Django 5.2.4 on 2025-07-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_cans_question_question_remove_question_opt1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='loginid',
        ),
        migrations.AddField(
            model_name='admin',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
