# Generated by Django 5.2.4 on 2025-07-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='cans',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opt4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='correctanswer',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='unknown;', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
